baseurl = "https://almostadatascientist.github.io/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "../almostadatascientist.github.io/"
author = "Jean Souza"
title = "A Data Science Odyssey"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
custom_css = ['css/custom_styling.css']
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Such a good place to stay."
copyright = "Copyright © 2017 Jean Souza"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/ass_jean.png"
faviconfile = "bottle.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "almostadatascientist"
email = "jeanccarlos.ds@gmail.com.com"
linkedin = "john-example-aa80ue8è"
twitter = "example"
facebook = "facebook_id"
social_banner = "bottle.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
